version: '3.8'

services:
  app:
    image: hibaalaouii/devops-integration:latest
    ports:
      - "8081:8080"  # expose le port 8080 du container sur 8081 de ta machine (choisis un port libre)
    restart: always
